#!/bin/bash

# Author: Thang Duong
# Practicing classical FOR loop


if [[ $# -ne 2 ]]; then
    echo "Need exactly two arguments!!!"
fi


for f in *"$1"; do
    base=$(basename "$f" "$1")
    mv "$f" "${base}$2"
done

exit 0
