#!/bin/bash
# Author: Thang Duong
# Compare number of files of two folders
# stuck here

# Check number of arguments
if [[ $# -ne 2 ]]; then
    echo "Exactly 2 arguments required!!!"
	exit 1
fi


# Check both arguments is directory
if [[ ! -d $1 ]]; then
    echo "$1 is not a directory"
    exit 1
fi

if [[ ! -d $2 ]]; then
    echo "$2 is not a directory"
	exit 1
fi

dir1="$1"
dir2="$2"

# Get number of files in 2 directories
count_1=$(ls -A1 "$dir1" | wc -l)
count_2=$(ls -A1 "$dir2" | wc -l)

# Comparing
if [[ $count_1 -gt $count_2 ]]; then
    echo "$dir1 has more files than $dir2"
elif [[ $count_2 -gt $count_1 ]]; then
    echo "$dir2 has more files than $dir1"
else
    echo "Equal!!!"
fi

exit 0
