#!/bin/bash

# Author: Thang Duong
# Keep learning if, elif, else

# Check number of arguments
if [[ $# -ne 2 ]]; then
    echo "Need exactly two arguments!!!"
    exit 1
fi

string1=${#1}
string2=${#2}

# Compare two strings
if [[ $string1 -gt $string2 ]]; then
    echo "First string is longer than second string"
elif [[ $string1 -lt $string2 ]]; then
    echo "Second string is longer than first string"
else
    echo "Two strings are equal!"
fi

exit 0
