#!/bin/bash

# Author: Thang Duong
# Learning manipulating variable with SHIFT

# Is there an argument?
if [[ ! $1 ]]; then
    echo "Missing argument!!!" >&2
    exit 1
fi

declare open_editor=""
if [[ $# -eq 1 ]]; then
    open_editor="true"
fi

declare -r bindir="${HOME}/Desktop/bin"


# Check bin directory existence
if [[ ! -d $bindir ]]; then
    # if not, create one
    if mkdir "$bindir"; then
        echo "Directory ${bindir} created"
    else
        echo "Could not create ${bindir}" >&2
        exit 1
    fi
fi

while [[ $1 ]]; do
    scriptname="$1"
    filename="${bindir}/${scriptname}"

    if [[ -e $filename ]]; then
        echo "File ${filename} already exists" >&2
        shift
        continue
    fi

    if type "$scriptname" > /dev/null 2>&1; then
        echo "There is already a command with name ${scriptname}" >&2
        shift
        continue
    fi

    # Create script with a single line
    echo '#!/bin/bash' > "$filename"
    # Grant permission
    chmod u+x "$filename"

    shift
done

# Open with an editor
if [[ $open_editor ]]; then
    echo opening
    
    if [[ $EDITOR ]]; then
        $EDITOR "$filename"
    else
        echo "Editor is not set" >&2
        exit 1
    fi
fi

exit 0
