#!/bin/bash
# Author: Thang Duong
# Just a simple CASE

if [[ ! $1 ]]; then
    echo "Need exactly 1 argument!!!" >&2
    exit 1
fi

case $1 in
    cat)
        echo "meow";;
    dog)
        echo "woof";;
    cow)
        echo "mooo";;
    *)
        echo "Unknown creature!!!"
esac

exit 0
