#!/bin/bash

# Author: Thang Duong
# Practicing CONTINUE

if [[ ! $1 ]]; then
    echo "Need first argument" >&2
    exit 1
fi

found="z"

# read upto first match
while read -r; do
    if [[ ! $found ]]; then
        if [[ $REPLY =~ $1 ]]; then
            found="yep"
        else
            continue
        fi
    fi
echo "$REPLY"
done

exit 0
